### ISSUE TITLE
Outline broken with new Offset fix

### ISSUE THREAD

**Issue by dimosoff** [leotorrez/LeoTools#12]
I was update all files from  [b9d3005](https://github.com/leotorrez/LeoTools/commit/b9d3005cc3e2862a3cd6c2b77786527c8a9939fe) and these works great except [Offset.ini](https://github.com/leotorrez/LeoTools/blob/main/releases/Offset.ini).
When you choose a character it's all great for the first second but then [outline turns into mess](https://drive.google.com/uc?id=1d6gvmIE4t0OB4JuVHUS-oxSsNWoLx383).
TexFx is also latest version 1.05109.

**Comment by DodgeTheDarins** [comment]
Same, the offset.ini does not work for me either

**Comment by leotorrez** [comment]
You have to clean your /ShaderFixes folder for this latest update

**Comment by dimosoff** [comment]
> You have to clean your /ShaderFixes folder for this latest update

Yep, made it several times. It doesn't help.
