### ISSUE TITLE
Mod glitches with latest versions of Orfix.ini

### ISSUE THREAD

**Issue by Doredialilligan5** [leotorrez/LeoTools#2]
Hi! I've been having problems with Orfix.ini in its latests versions. Since the hash change because of the 4.2 update, some of my installed mods have been having problems. I must say that I have all my mods updated to 4.3.

As an example, the Focalors mod works perfectly fine with the old Orfix.ini with hash **26f0efad15c126ce**, but not with the new **e795de98764fb2b9**:
![Sin título-1](https://github.com/leotorrez/LeoTools/assets/155543512/fe78c1c7-8901-4afe-9562-6a618fe0e159)
As you can see, with the new hash Furina's hair is visible in her Pneuma Form.

Also, if I use the **shaderfixes** and **offsetfix.ini** provided, this "glowing traces effect" happens with both old and new Orfix.ini when looking at the animation from the top:
![Captura de pantalla (130)](https://github.com/leotorrez/LeoTools/assets/155543512/8563cdbe-b3c0-499b-a8a1-12af99db521c)

I don't think it is a glitch from the mod since it is updated to 4.3 and everything worked well with the previous hash. This is the mod I'm using btw:
https://gamebanana.com/mods/480406 (archonfurina.zip)

**Comment by leotorrez** [comment]
I am unable to replicate this error. Can you please check with only this mod and orfix in your mod folder to verify there is no other mod messing with your set up?

**Comment by Doredialilligan5** [comment]
With latest ORFix.ini, offsetfix.ini and ShaderFixes the yellow rays are gone. The problem was a Slplendor of Tranquil Waters mod. I changed the hashes for it to replace Wold Fang and it looks like I did something wrong.

The twin tails shadow still shows up, so I dont know what could be the problem :(

**Comment by leotorrez** [comment]
sorry for the delayed reply- at the time i didnt know what you meant. Now that I look closer i can see what you mean.


add $\global\ORFix\active=0 in the ponytail section to avoid orfix from applying to it
