### ISSUE TITLE
Offset scale changer moves the bottom hands but not shogun herself

### ISSUE THREAD

**Issue by chanhh01** [leotorrez/LeoTools#3]
Model with offset + your offset-scale changer:
![Model with offset + your offset-scale changer](https://github.com/leotorrez/LeoTools/assets/84566394/2730bd28-b3b0-4195-9396-8aed6f5eb28d)

Model with offset without offset-scale changer:
![Model with offset without offset-scale changer](https://github.com/leotorrez/LeoTools/assets/84566394/880ddfa6-fdc1-4aad-9c81-837deb2cc695)

**Comment by leotorrez** [comment]
You installed required files wrongly. You are missing the ones that go into shaderfixes.

**Comment by chanhh01** [comment]
> You installed required files wrongly. You are missing the ones that go into shaderfixes.

It worked partially for me for some reason.

![image](https://github.com/leotorrez/LeoTools/assets/84566394/7849d41c-3373-4c89-8e46-f278d3cf49e7)

**Comment by leotorrez** [comment]
The face being broken is due to 4.3 breaking IB hashes- you will have to manually update the face iB hashes in the ini file or check the original download page for an update on the mod
