### ISSUE TITLE
Reflection is ok, but the outline is not.

### ISSUE THREAD

**Issue by dimosoff** [leotorrez/LeoTools#5]
![изображение](https://github.com/user-attachments/assets/664d84e2-4284-4c26-b04f-206a0b05435d)
What could be the problem? I have the last versions of 3dmigoto, ORFix and TextFX.
Navia just as a example. Clorinde and Candice are also have wrong outline colors.
![изображение](https://github.com/user-attachments/assets/e81a5bb1-99d0-418f-9437-bbde7185bcd5)
I'll give u any extra info if needed.

**Comment by leotorrez** [comment]
texfx as experimenting some issues. Try to update to the latest one uploaded recently and let me know if it fixes your issue

**Comment by dimosoff** [comment]
> texfx as experimenting some issues. Try to update to the latest one uploaded recently and let me know if it fixes your issue

The problem was in ORFix.ini after all. I replaced the file with version 0.2.1 and the outlines were fixed without replacing TexFX. However, I then replaced it too.
Thank you for your work!
