### ISSUE TITLE
Outline bug? 

### ISSUE THREAD

**Issue by Entity378** [leotorrez/LeoTools#6]
For some reason when using this navia custom skin for the first second it is on screen the outlines are not "fixed" by ORFix. I tried to investigate and fix the problem myself but I couldn't do anything. This is the video I made where you can see what happens to the outline: 

https://github.com/user-attachments/assets/9e4ef011-1daa-484c-9664-98bbae441ad1

**Comment by leotorrez** [comment]
known issue. It is broken for half a second when you first spawn a character. Being it only on outline I decided to live with it, the extra effort to patch it every time is not worth the gain

**Comment by Entity378** [comment]
If I wanted to fix the problem myself, what should I do? (I ask because you seem to know how to fix the problem)
Anyway, thanks for replying

**Comment by leotorrez** [comment]
Hunt for that elusive hash and add it to orfix

**Comment by Entity378** [comment]
found the hash. If you want to add it, this is it:
```
ShaderOverrideOutlinePSOutline]
hash = 599092b725a44f2a
allow_duplicate_hash = overrule
filter_index = 037730.0
```

**Comment by leotorrez** [comment]
Appreciated but I pass. My stance on the subject remains the same
