### ISSUE TITLE
offsetfix 3.9 broke natlan nightsoul on modded characters

### ISSUE THREAD

**Issue by chairmanxyz** [leotorrez/LeoTools#7]
![Screenshot 2024-10-11 214145](https://github.com/user-attachments/assets/1ad45886-382d-4c12-92ec-878020a60074)
![Screenshot 2024-10-11 213945](https://github.com/user-attachments/assets/4837b806-3da9-4181-b1bc-f27e69b28849)
Issue is on all 4 Natlan characters during nightsoul. The outline appears in black instead of the normal color. Works correctly in 3.8.

I tried clearing shadercache and made sure I'm using the new shaderfixes. Orfix is version 0.2.4.

**Comment by leotorrez** [comment]
yeah it does break it- I am working on a fix but will take time

**Comment by chairmanxyz** [comment]
I think we can close this now :) Your tip on discord to clear the shaderfixes folder fixed all my issues. Running 3.9.3 perfectly.
